### ISSUE TITLE
Don't touch actual CommonJS files

### ISSUE THREAD

**Issue by tunnckoCore** [WebReflection/ascjs#10]
Use case, you have ES Modules files in `src`, but there you also have `src/cli.js` which is actual real cjs file with shebang.

I propose to skip such files that don't have `import/export`s, so just copy them without transforming them.

Say you have this `src/cli.js`

```js
#!/usr/bin/env node

'use strict';

const proc = require('process');

// ... cli code
```

it gets transformed to invalid bin file

```js
'use strict';
#!/usr/bin/env node

'use strict';

const proc = require('process');

// ... rest
```

**Comment by tunnckoCore** [comment]
Or at least, support ignoring files.

**Comment by tunnckoCore** [comment]
I think we can use `fast-glob` or such, to get all needed files and then transform them.

**Comment by WebReflection** [comment]
2.5 doesn't ruin shebang on top, ignores already strict files, and the binary has now an `--ignore=one.js,ormore.js,files.js` flag.

**Comment by tunnckoCore** [comment]
Thanks, just commented one thing.
