### ISSUE TITLE
Watch flag

### ISSUE THREAD

**Issue by bcomnes** [WebReflection/ascjs#16]
Problem: when I develop an esm module back-ported to cjs with ascjs, I sometimes link the module to a local consumer module that is running in cjs mode.  When I modify the esm module, I forget to re-compile the cjs version and end up pulling out my hair when it doesn't change things like I expect, and then eventually remember to recompile.  (Has happened 2-3 time now 😅)

Possible solution:  add a watch flag to ascjs.  This way, when working on the esm portion, any file changes will trigger a cjs rebuild automatically.  That way if I have the module linked to cjs consumers, I don't have to manually trigger rebuilds.  

Would you be interested in that addition and do you have any thoughts on how you would like that done?

**Comment by WebReflection** [comment]
can't you just create a script that watch yout esm folder and run `ascjs esm cjs` on changes? the whole point of this project, as well as ucjs, is to keep it simple https://medium.com/@WebReflection/unpopular-metrics-about-js-bundlers-a3c56ea5390d

watching recursively has always been a pain due non standardization across OS, I am not sure I want to maintain that bit, as there are other solutions to this, I hope you understand.

**Comment by bcomnes** [comment]
Yeah but it’s just more setup overhead per module using ascjs.  Know of any good tools on npm that can do that? Vaguely recall nodemon had something like that.

**Comment by WebReflection** [comment]
if you have a `"cjs": "ascjs esm cjs"` entry in you `package.json`, you could as well have a:

```
"esm:watch": "node -e 'require(`fs`).watch(`esm`,{recursive:!0},()=>require(`child_process`).execSync(`npm run cjs`))'"
```

whenever you are developing you can `npm run esm:watch` and call it a day, wouldn't that work?

**Comment by bcomnes** [comment]
It works but wouldn't support partial regeneration (e.g. just rebuild the file that changed) and it's a lot to remember/type when setting up fresh package.jsons.   Thinking I'll wrap that or something similar up in an 'alias' or wrapper tool so the guts aren't exposed.

**Comment by WebReflection** [comment]
> It works but wouldn't support ...

this is the "_born to be simple_" bit I was talking about ... if you need complicated setups, go rollup/webpack/others, but if you can keep it simple, this is likely the right project 😉
