### ISSUE TITLE
Namespace semantics

### ISSUE THREAD

**Issue by robpalme** [WebReflection/ascjs#3]
The following lines are not equivalent because namespace objects do not contain default exports. 

import * as tmp from 'other';
const tmp = require('other');

It would be possible to add some conditional handling for the case where 'other' is found to be an ES module. Let me know if you are interested in PRs for this kind of thing.

**Comment by WebReflection** [comment]
AFAIK those lines are fine, but if you want to be sure everything is imported/exported as CJS you should use [asbundle](https://github.com/WebReflection/asbundle) instead.

```js
// index.js
import * as test from './test.js';
console.log(test);

// test.js
const a = 1, b = 2;
export {a, b};
```

The result is an object with both `a` and `b` properties so everything is fine.

Using `asbundle index.js` produces the following bundle:
```js
((cache, modules) => {
  const require = i => cache[i] || get(i);
  const get = i => {
    const exports = {};
    const module = {exports};
    modules[i].call(exports, window, require, module, exports);
    return (cache[i] = module.exports);
  };
  const main = require(0);
  return main.__esModule ? main.default : main;
})([],[function (global, require, module, exports) {
// index.js
'use strict';
const test = require(1);

console.log(test);
},function (global, require, module, exports) {
// test.js
'use strict';
const a = 1, b = 2;
exports.a = a;
exports.b = b;
}]);
```
You can run it manually and see same result.
